[package]
name = "dapr_echo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
hyper_wasi = { version = "0.15", features = ["full"] }
tokio_wasi = { version = "1.21", features = ["rt", "macros", "net", "time"]}
dapr_sdk_wasi = { path = "../../" }
